---
#######################
# Rubocop Config file #
#######################

inherit_gem:
  rubocop-github:
    - config/default.yml
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false